#ifndef CONFIGMATH_H
#define CONFIGMATH_H

#define ENGINE_MATH_NATIVE 1
#define ENGINE_MATH_SSE 2
#define ENGINE_MATH_DIRECTXMATH 3
#define ENGINE_MATH_D3DXMATH 4

#include "configGFX.h"
#if ENGINE_GFX == ENGINE_GFX_DX_11
#define ENGINE_MATH ENGINE_MATH_NATIVE
#elif ENGINE_GFX == ENGINE_GFX_DX_10
#define ENGINE_MATH ENGINE_MATH_D3DXMATH
#else
#endif

#endif